/* Auto-generated by tools/diorama_rules/compile_rules.py. Do not edit. */
#ifndef GUARD_DIORAMA_RULES_GENERATED_H
#define GUARD_DIORAMA_RULES_GENERATED_H
#include <stddef.h>
#include <stdint.h>

struct DioramaGeneratedTilesetV2 { uint8_t id, role; uint16_t metatileCount; const char *symbol; };
struct DioramaGeneratedLayoutV2 { uint16_t id; uint8_t primaryTilesetId, secondaryTilesetId; const char *symbol; };
struct DioramaGeneratedMapV2 { uint8_t group, number, supported, cameraProfile, mapType, groundMode; uint16_t layoutId, groundMetatile, mapScopeId; uint32_t contextualRuleOffset, exactPatternOffset; uint16_t contextualRuleCount, exactPatternCount; float pitchRadians, focalLength; const char *symbol, *unsupportedReason; };
struct DioramaGeneratedActionV2 { uint8_t archetypeId, poolId, profileId, axis, groundMode, terrainClass; uint16_t groundMetatile, flags; float groundOffset, height; };
struct DioramaGeneratedBehaviorRuleV2 { uint8_t behavior; uint32_t placementCount; const char *allowedUnusedReason; struct DioramaGeneratedActionV2 action; };
struct DioramaGeneratedPoolV2 { uint16_t id; const char *logicalId, *description; };
struct DioramaGeneratedProfileV2 { uint16_t id; uint8_t archetypeId; uint32_t maskOffset, sampleOffset; uint16_t maskCount, sampleCount; const char *logicalId; };
struct DioramaGeneratedMaskV2 { uint16_t profileId; uint8_t kind, width, height; uint32_t rowOffset; uint16_t rowCount; };
struct DioramaGeneratedSampleV2 { uint8_t tilesetId, layer; uint16_t metatile; };
struct DioramaGeneratedTilesetPinV2 { uint8_t tilesetId; uint16_t metatile; uint32_t placementCount; const char *allowedUnusedReason; struct DioramaGeneratedActionV2 action; };
struct DioramaGeneratedNeighborV2 { uint8_t direction, flags, behavior, layer, elevation; uint16_t metatile; };
struct DioramaGeneratedSelectorV2 { uint32_t tilesetOffset, metatileOffset, behaviorOffset, layerOffset, elevationOffset, mapTypeOffset, neighborOffset; uint16_t tilesetCount, metatileCount, behaviorCount, layerCount, elevationCount, mapTypeCount, neighborCount; uint8_t eventKind; const char *eventClass; };
struct DioramaGeneratedContextualRuleV2 { uint16_t id, mapScopeId, selectorId; int16_t priority; uint32_t placementCount; const char *logicalId, *allowedUnusedReason; struct DioramaGeneratedActionV2 action; };
struct DioramaGeneratedExactPatternV2 { uint16_t id, mapScopeId; uint8_t primaryTilesetId, secondaryTilesetId, width, height; int16_t priority; uint32_t cellOffset, claimOffset, placementCount; const char *logicalId, *allowedNoPlacementsReason; struct DioramaGeneratedActionV2 action; };
struct DioramaGeneratedEventPresetV2 { uint16_t id; uint8_t eventKind; uint32_t placementCount; const char *logicalId, *eventClass, *allowedUnusedReason; struct DioramaGeneratedActionV2 action; };

extern const char gDioramaRulesSha256[65];
extern const uint32_t gDioramaRulesGeneration;
extern const struct DioramaGeneratedTilesetV2 gDioramaTilesetsV2[];
extern const size_t gDioramaTilesetV2Count;
extern const struct DioramaGeneratedLayoutV2 gDioramaLayoutsV2[];
extern const size_t gDioramaLayoutV2Count;
extern const struct DioramaGeneratedMapV2 gDioramaMapsV2[];
extern const size_t gDioramaMapV2Count;
extern const struct DioramaGeneratedActionV2 gDioramaDefaultActionV2;
extern const struct DioramaGeneratedBehaviorRuleV2 gDioramaBehaviorRulesV2[];
extern const size_t gDioramaBehaviorRuleV2Count;
extern const struct DioramaGeneratedPoolV2 gDioramaPoolsV2[];
extern const size_t gDioramaPoolV2Count;
extern const struct DioramaGeneratedProfileV2 gDioramaProfilesV2[];
extern const size_t gDioramaProfileV2Count;
extern const struct DioramaGeneratedMaskV2 gDioramaMasksV2[];
extern const size_t gDioramaMaskV2Count;
extern const uint64_t gDioramaMaskRowsV2[];
extern const size_t gDioramaMaskRowV2Count;
extern const struct DioramaGeneratedSampleV2 gDioramaSamplesV2[];
extern const size_t gDioramaSampleV2Count;
extern const struct DioramaGeneratedTilesetPinV2 gDioramaTilesetPinsV2[];
extern const size_t gDioramaTilesetPinV2Count;
extern const struct DioramaGeneratedSelectorV2 gDioramaSelectorsV2[];
extern const size_t gDioramaSelectorV2Count;
extern const uint8_t gDioramaSelectorTilesetsV2[], gDioramaSelectorBehaviorsV2[], gDioramaSelectorLayersV2[], gDioramaSelectorElevationsV2[], gDioramaSelectorMapTypesV2[];
extern const uint16_t gDioramaSelectorMetatilesV2[];
extern const size_t gDioramaSelectorTilesetV2Count, gDioramaSelectorMetatileV2Count, gDioramaSelectorBehaviorV2Count, gDioramaSelectorLayerV2Count, gDioramaSelectorElevationV2Count, gDioramaSelectorMapTypeV2Count;
extern const struct DioramaGeneratedNeighborV2 gDioramaNeighborsV2[];
extern const size_t gDioramaNeighborV2Count;
extern const struct DioramaGeneratedContextualRuleV2 gDioramaContextualRulesV2[];
extern const size_t gDioramaContextualRuleV2Count;
extern const uint16_t gDioramaPatternCellsV2[];
extern const uint8_t gDioramaPatternClaimsV2[];
extern const size_t gDioramaPatternCellV2Count, gDioramaPatternClaimV2Count;
extern const struct DioramaGeneratedExactPatternV2 gDioramaExactPatternsV2[];
extern const size_t gDioramaExactPatternV2Count;
extern const struct DioramaGeneratedEventPresetV2 gDioramaEventPresetsV2[];
extern const size_t gDioramaEventPresetV2Count;
#endif
