/* Auto-generated by tools/diorama_rules/compile_rules.py. Do not edit. */
#ifndef GUARD_DIORAMA_RULES_GENERATED_H
#define GUARD_DIORAMA_RULES_GENERATED_H
#include <stddef.h>
#include <stdint.h>

struct DioramaGeneratedTilesetV2 { uint8_t id, role, terrainClass; uint16_t metatileCount; const char *symbol; };
struct DioramaGeneratedLayoutV2 { uint16_t id, width, height; uint8_t primaryTilesetId, secondaryTilesetId; uint32_t terrainRecordOffset, terrainRecordCount, structureCellOffset; const char *symbol; };
struct DioramaGeneratedTerrainV2 { uint32_t cellOffset; uint16_t expectedMetatile, classId, sourceId, evidenceDetailsId, ambiguityDetailsId, propGroundMetatile, evidenceFlags, ambiguityFlags; int16_t heightQ16; uint8_t mapGroup, mapNumber, shape, archetype, terrainClass, artMode, pool, authored, sourceKind, propGroundMode, axis, cliffEdgeMask, cliffBaseMask, cliffTransitionMask, cliffCornerMask; float confidence; };
struct DioramaGeneratedClassifierSourceV2 { uint16_t id; const char *name; };
struct DioramaGeneratedEvidenceV2 { uint16_t id; const char *details; };
struct DioramaGeneratedAmbiguityV2 { uint16_t id, flags; uint32_t placementCount; const char *details; };
struct DioramaGeneratedMapV2 { uint8_t group, number, supported, cameraProfile, mapType, groundMode; uint16_t layoutId, groundMetatile; float pitchRadians, focalLength; const char *symbol, *unsupportedReason; };
struct DioramaGeneratedPoolV2 { uint16_t id; const char *logicalId, *description; };
struct DioramaGeneratedProfileV2 { uint16_t id; uint8_t archetypeId; uint32_t maskOffset, sampleOffset; uint16_t maskCount, sampleCount; const char *logicalId; };
struct DioramaGeneratedMaskV2 { uint16_t profileId; uint8_t kind, width, height; uint32_t rowOffset; uint16_t rowCount; };
struct DioramaGeneratedSampleV2 { uint8_t tilesetId, layer; uint16_t metatile; };
struct DioramaGeneratedStructureV2 { uint16_t id, layoutId; uint8_t mapGroup, mapNumber, kind, pool, classId, claimOnly; int16_t priority, x, y; uint8_t width, height; uint32_t cellOffset, cellCount, visiblePixels, transparentPixels, blackPixels, pixelComponents; const char *owner, *source, *evidence; };
struct DioramaGeneratedStructureCellV2 { uint16_t claimOwner, regionId; uint8_t doorFold, voidKind; };
struct DioramaGeneratedStructureOverrideV2 { uint16_t layoutId, expectedMetatile; uint32_t cellOffset; uint8_t mapGroup, mapNumber; struct DioramaGeneratedStructureCellV2 cell; };
struct DioramaGeneratedPixelObjectV2 { uint16_t id, structureId, supportStructureId, layoutId, groundMetatile, spriteDepthBiasMillionths; uint8_t mapGroup, mapNumber, kind, pool, classId, componentCount, width, height, groundMode; int16_t supportOffsetQ16; uint32_t pixelOffset, pixelCount, maskOffset, maskCount; };
struct DioramaGeneratedPixelV2 { uint32_t sourceCellOffset; uint16_t expectedMetatile, expectedTileEntry, sourceTile; int16_t xQ32, yQ32, zQ32; uint8_t sizeXQ32, sizeYQ32, sizeZQ32, sourceLayer, sourceSubtile, sourcePalette, sourceColor, sourceU, sourceV, sourceX, sourceY, component; };

extern const char gDioramaRulesSha256[65];
extern const uint32_t gDioramaRulesGeneration;
extern const struct DioramaGeneratedTilesetV2 gDioramaTilesetsV2[];
extern const size_t gDioramaTilesetV2Count;
extern const struct DioramaGeneratedLayoutV2 gDioramaLayoutsV2[];
extern const size_t gDioramaLayoutV2Count;
extern const struct DioramaGeneratedTerrainV2 gDioramaTerrainV2[];
extern const size_t gDioramaTerrainV2Count;
extern const struct DioramaGeneratedClassifierSourceV2 gDioramaClassifierSourcesV2[];
extern const size_t gDioramaClassifierSourceV2Count;
extern const struct DioramaGeneratedEvidenceV2 gDioramaEvidenceDetailsV2[];
extern const size_t gDioramaEvidenceDetailV2Count;
extern const struct DioramaGeneratedAmbiguityV2 gDioramaAmbiguitiesV2[];
extern const size_t gDioramaAmbiguityV2Count;
extern const struct DioramaGeneratedMapV2 gDioramaMapsV2[];
extern const size_t gDioramaMapV2Count;
extern const struct DioramaGeneratedPoolV2 gDioramaPoolsV2[];
extern const size_t gDioramaPoolV2Count;
extern const struct DioramaGeneratedProfileV2 gDioramaProfilesV2[];
extern const size_t gDioramaProfileV2Count;
extern const struct DioramaGeneratedMaskV2 gDioramaMasksV2[];
extern const size_t gDioramaMaskV2Count;
extern const uint64_t gDioramaMaskRowsV2[];
extern const size_t gDioramaMaskRowV2Count;
extern const struct DioramaGeneratedSampleV2 gDioramaSamplesV2[];
extern const size_t gDioramaSampleV2Count;
extern const struct DioramaGeneratedStructureV2 gDioramaStructuresV2[];
extern const size_t gDioramaStructureV2Count;
extern const uint32_t gDioramaStructureCellsV2[];
extern const size_t gDioramaStructureCellV2Count;
extern const struct DioramaGeneratedStructureCellV2 gDioramaStructureOwnersV2[];
extern const size_t gDioramaStructureOwnerV2Count;
extern const struct DioramaGeneratedStructureOverrideV2 gDioramaStructureOverridesV2[];
extern const size_t gDioramaStructureOverrideV2Count;
extern const struct DioramaGeneratedPixelObjectV2 gDioramaPixelObjectsV2[];
extern const size_t gDioramaPixelObjectV2Count;
extern const struct DioramaGeneratedPixelV2 gDioramaPixelsV2[];
extern const size_t gDioramaPixelV2Count;
extern const uint64_t gDioramaPixelMaskRowsV2[];
extern const size_t gDioramaPixelMaskRowV2Count;
#endif
