/* Auto-generated by tools/diorama_rules/compile_rules.py. Do not edit. */
#ifndef GUARD_DIORAMA_RULES_GENERATED_H
#define GUARD_DIORAMA_RULES_GENERATED_H

#include <stddef.h>
#include <stdint.h>
#include "diorama/rules.h"

extern const uint32_t gDioramaRulesGeneration;
extern const struct DioramaRuleDefinition gDioramaDefaultRule;
extern const struct DioramaGeneratedLayoutRule gDioramaLayoutRules[];
extern const size_t gDioramaLayoutRuleCount;
extern const struct DioramaGeneratedMapRule gDioramaMapRules[];
extern const size_t gDioramaMapRuleCount;
extern const struct DioramaGeneratedBehaviorRule gDioramaBehaviorRules[];
extern const size_t gDioramaBehaviorRuleCount;
extern const struct DioramaGeneratedTilesetRule gDioramaTilesetRules[];
extern const size_t gDioramaTilesetRuleCount;
extern const struct DioramaGeneratedMapOverride gDioramaMapOverrides[];
extern const size_t gDioramaMapOverrideCount;
extern const struct DioramaGeneratedBuildingTemplate gDioramaBuildingTemplates[];
extern const size_t gDioramaBuildingTemplateCount;
extern const struct DioramaGeneratedBuildingPlacement gDioramaBuildingPlacements[];
extern const size_t gDioramaBuildingPlacementCount;

#endif
