#!/usr/bin/env python3
"""Generate src/data/ax_map_names.h -- spoken map names for the accessible port.

The game's map header only carries a region-map section id, so every room inside
Littleroot would otherwise announce as plain "Littleroot Town". The map *names*
we want ("Brendan's House 1F") only exist in data/maps/map_groups.json, so we
bake them into a [group][num] string table the screen reader can index directly.

Re-run this by hand after adding or renaming maps:

    python tools/gen_ax_map_names.py
"""

import json
import os
import re

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO, "data", "maps", "map_groups.json")
DST = os.path.join(REPO, "src", "data", "ax_map_names.h")

# Words the CamelCase splitter would otherwise mangle into single letters.
KEEP_WHOLE = {
    "1F": "1F", "2F": "2F", "3F": "3F", "4F": "4F", "5F": "5F",
    "6F": "6F", "7F": "7F", "8F": "8F", "9F": "9F",
    "B1F": "B1F", "B2F": "B2F", "B3F": "B3F", "B4F": "B4F",
    "PC": "PC", "TV": "TV", "SS": "S S",
}

# Names that read badly once split; spell them the way they should be spoken.
FIXUPS = [
    (r"\bPokemon Center\b", "Pokemon Center"),
    (r"\bPoke Center\b", "Pokemon Center"),
    (r"\bMart\b", "Mart"),
    (r"\bBrendans\b", "Brendan's"),
    (r"\bMays\b", "May's"),
    (r"\bRivals\b", "Rival's"),
    (r"\bPlayers\b", "Player's"),
    (r"\bBirchs\b", "Birch's"),
    (r"\bLab\b", "Lab"),
    (r"\bRoute(\d+)\b", r"Route \1"),
]


def split_camel(token):
    """LittlerootTown -> 'Littleroot Town'; digits stay glued to their word."""
    if token in KEEP_WHOLE:
        return KEEP_WHOLE[token]
    # Split before an uppercase letter that follows a lowercase/digit, and
    # before the last uppercase of an acronym run that precedes a lowercase.
    s = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", token)
    s = re.sub(r"(?<=[A-Z])(?=[A-Z][a-z])", " ", s)
    return s


def pretty(map_name):
    """LittlerootTown_BrendansHouse_1F -> "Littleroot Town, Brendan's House, 1F"."""
    parts = [split_camel(p) for p in map_name.split("_") if p]
    text = ", ".join(p for p in parts if p)
    for pattern, repl in FIXUPS:
        text = re.sub(pattern, repl, text)
    return re.sub(r"\s+", " ", text).strip()


def c_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    with open(SRC, "r", encoding="utf-8") as f:
        data = json.load(f)

    groups = data["group_order"]
    out = [
        "// Generated by tools/gen_ax_map_names.py -- do not edit by hand.",
        "// Spoken map names, indexed by [map group][map number].",
        "",
    ]

    for i, group in enumerate(groups):
        maps = data[group]
        out.append("static const char *const sAxMapNames_%d[] = {" % i)
        for m in maps:
            out.append("    %s," % c_string(pretty(m)))
        out.append("};")
        out.append("")

    out.append("static const char *const *const sAxMapNames[] = {")
    for i in range(len(groups)):
        out.append("    sAxMapNames_%d," % i)
    out.append("};")
    out.append("")
    out.append("static const u16 sAxMapNameCounts[] = {")
    for group in groups:
        out.append("    %d," % len(data[group]))
    out.append("};")
    out.append("")
    out.append("#define AX_MAP_GROUP_COUNT %d" % len(groups))
    out.append("")

    with open(DST, "w", encoding="utf-8") as f:
        f.write("\n".join(out))

    total = sum(len(data[g]) for g in groups)
    print("wrote %s (%d groups, %d maps)" % (DST, len(groups), total))


if __name__ == "__main__":
    main()
